-- Migration: Add blog-related columns for SEO content
-- Date: 2026-02-07
-- Description: Adds columns for SEO blog content generated by Gemma 3

-- Add SEO blog columns
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS meta_description TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS blog_article TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS highlights JSONB;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS faqs JSONB;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS data_source TEXT;

-- Add comments for documentation
COMMENT ON COLUMN jobs.seo_title IS 'SEO-optimized title for the job (60-70 chars)';
COMMENT ON COLUMN jobs.meta_description IS 'Meta description for SEO (150-160 chars)';
COMMENT ON COLUMN jobs.blog_article IS 'Full blog article in markdown format (800-1000 words)';
COMMENT ON COLUMN jobs.highlights IS 'Array of key highlights (5 points)';
COMMENT ON COLUMN jobs.faqs IS 'Array of FAQs with questions and answers';
COMMENT ON COLUMN jobs.data_source IS 'Source of data extraction: pdf_gemma3, html_css';

-- Create index for faster blog content queries
CREATE INDEX IF NOT EXISTS idx_jobs_data_source ON jobs(data_source);

-- Add constraint for data_source values
ALTER TABLE jobs ADD CONSTRAINT check_data_source 
    CHECK (data_source IN ('pdf_gemma3', 'html_css', NULL));

-- Update existing records to set data_source (optional)
UPDATE jobs SET data_source = 'html_css' WHERE data_source IS NULL;

-- Verify migration
SELECT 
    column_name, 
    data_type, 
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'jobs' 
    AND column_name IN (
        'seo_title',
        'meta_description',
        'blog_article',
        'highlights',
        'faqs',
        'data_source'
    )
ORDER BY ordinal_position;
